### PR TITLE
Fix incorrect image tensor shape

### LINKED ISSUE #126: Wrong shape returned from write_to_tensor/1
It looks like the binary data returned by `Vix.Vips.Image.write_to_tensor/1` has HWC order, but the returned shape is WHC.

Reproduction:

````livemd
# Vix image to tensor

```elixir
Mix.install([
  {:kino, "~> 0.10.0"},
  {:vix, "~> 0.22.0"},
  {:req, "~> 0.4.4"},
  {:nx, "~> 0.6.2"}
])
```

## 🐈‍⬛

```elixir
%{body: binary} =
  Req.get!(
    "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2F0fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60"
  )
```

```elixir
{:ok, image} = Vix.Vips.Image.new_from_buffer(binary)
image
```

```elixir
{:ok, %Vix.Tensor{data: data, shape: shape, names: names, type: type}} =
  Vix.Vips.Image.write_to_tensor(image)
```

```elixir
tensor = data |> Nx.from_binary(type) |> Nx.reshape(shape)
Kino.Image.new(tensor)
```

```elixir
{width, height, channels} = shape
tensor = data |> Nx.from_binary(type) |> Nx.reshape({height, width, channels})
Kino.Image.new(tensor)
```
````

*Originally came up in [this thread](https://elixirforum.com/t/image-to-text-model-recommendation/58763).*

### PR DESCRIPTION
**Pull request by akash-akya**
Fixes #126 

Hi @kipcole9, can you check if this breaks something in image?

### CODE REVIEW

**Comment by kipcole9** [comment]
@akash-akya I will check in the next 24 hours. I suspect it will require an update on my side. And this may explain some unexpected behaviour I had to work around.  Will revert ASAP.

**Comment by kipcole9** [comment]
@akash-akya, I've updated [image](https://github.com/kipcole9/image) to reflect this change. As expected, I needed to modify `Image.to_nx/2` and `Image.from_nx/1`. 

I will publish an `image` update when you publish the update to `vix`.  Do you plan on setting the vix version to `0.23.0`?

**Comment by akash-akya** [comment]
Thanks for the update! I'll merge and push new version today

**Comment by akash-akya** [comment]
@kipcole9 `v0.23.1` is released. Please use `v0.23.1` (not `v0.23.0`) version, which contains a minor compilation fix. 🎉

**Comment by kipcole9** [comment]
I've published [image version 0.38.3](https://hex.pm/packages/image/0.38.3). Thanks for the early warning Akash, much appreciated.

**Pull request merged**
