### PR TITLE
Add draw_* operations to MutableImage

### PR DESCRIPTION
**Pull request by kipcole9**
Based upon a request I started working on adding the `draw_*` operations to `MutableImage`. This PR is not ready, but I did want to get your blessing to keep going to flesh out all the functions and add tests. 

I have an experimental `draw` branch of [Image](https://github.com/kipcole9/https://github.com/kipcole9/image/tree/draw) that calls these functions and so far it seems to work very well.  There is a [demo script]( https://github.com/kipcole9/image/blob/draw/bench/add_circles_to_image.exs) that executes in under 500ms to add 1000 circles of a random color and location and uses less than 3Mb of memory.

As always your guidance/corrections most welcome.

### CODE REVIEW

**Comment by akash-akya** [comment]
Hi @kipcole9, Thanks again for taking your time to help new features for vix! 
apologies for slow response. Bit busy with day job at the moment.

The main concern I have with mutable operations is (I think you are also aware of this) is that it is a bit tricky to ensure parallel libvips operations happening on the same memory. Using `MutableImage` is right direction, which you are already doing. But it would be great if we make it impossible to have that scenario. I mean, mutable operations should not even be visible in `Operation` module for someone to misuse unknowingly. But these can be addressed separately I think. The overall approach looks good to me.

I wasn't sure about performance and practicality of these operations given the constrains like using beam process for image. But based on your benchmark, seems it is not that bad when we are doing lot of mutable operations _at once_.(as opposed to mixed mutable, immutable operations)

I might take some time to test and benchmark. But feel free to explore and push changes. I'll make sure to get it merged ASAP.

**Comment by kipcole9** [comment]
Thanks for the guidance @akash-akya . Agree with the concerns over parallel operations and also performance.  Glad I'm heading in a reasonable direction.  I did see if omitting the `@doc` for these mutable operations was a possibility and then realised it needs a bit of work - something I can come back to later.

For performance, I built a small demo repo that matches what I was asked to look at. It streams a CSV file and plots 10_000 circles on an image.  The code is at https://github.com/kipcole9/cropping - if takes 4 seconds on my MacBook Pro (M1 Max) which I think is quite reasonable given all that is going on.  Performance seems linear (about 400ms for 1_000 circles) which is good to see. The README has the very simple instructions to run it.

Will keep going on the `draw_*` functions for now and let you know when I'm close enough to complete for a review.

Thanks again, --Kip

**Comment by akash-akya** [comment]
Hi @kipcole9, I looked into the changes. Overall, looks good to me.
I'm thinking of minor refactoring, like moving code around to make Vix prepared for mutable-operations. I'm thinking of creating a separate module for `MutableOperation` similar to `Operation`.

Can you take a look? -- https://github.com/akash-akya/vix/compare/master...draw
If it is okay then, I can merge this PR and make changes on top of that.

**Comment by kipcole9** [comment]
@akash-akya sounds great to me, very happy to follow your lead. You're much better at this than I am!

**Pull request merged**
