### PR TITLE
Fix return type for Vix.Vips.concurrency_get/0, support Kino.Render protocol

### PR DESCRIPTION
**Pull request by kipcole9**
* Add support for the `Kino.Render` protocol to render image metadata and the image in a Livebook.
* Fix the return type for `Vix.Vips.concurrency_get/0` to avoid dialyzer errors

As of [kino 0.7.0](https://hex.pm/packages/kino/0.7.0) the `Kino.Render` protocol can be implemented to render custom types. This PR adds support for `Vix.Vips.Image.t` images.  It produces two tabs: One with image metadata and the second with the image itself

### Metadata tab

image

### Image tab

image

### CODE REVIEW

**Comment by akash-akya** [comment]
@kipcole9 thanks again for the contribution! Supporting Kino render is my backlog from [sometime now.](https://github.com/akash-akya/kino_vix/blob/main/lib/render.ex)
 
One concern I have with render is that it forces the image pipeline to execute as soon as we return any `image` in any cell. In some cases, render intermediate stages can be an expensive operation. I am not sure if this is okay or not from user point of view. Maybe it is not a big concern, and we can have an option to turn it off. Just thinking out loud to get your view on this.

And, should we resize the image to an appropriate size while rendering? So it works well for a big image. I am comparing this with how generally image preview works in image processing context. And how `inspect(binary)` truncates the output for large binaries.

**Comment by kipcole9** [comment]
Good thoughts @akash-akya. I think given the interactive nature of Livebook that executing the render pipeline is ok.  Especially since there are `!` and `non-!` versions of most functions. Meaning that a user can control the expectation - `non-!` versions won't trigger the `Kino.Render` protocol for `Vix.Vips.Image.t`.

I had also thought about resizing automatically and concluded that is should be a user operation if they want to resize. But I can equally understand the other point of view.

In my own work I'm finding this output really useful for showing intermediate results during various image transforms. I haven't found any issues with execution time, nor yet from image size rendering. But I accept that others may feel differently.

Given Vix is still not at `1.x` its reasonable to go ahead without resizing and get further community feedback and preferences?

**Comment by akash-akya** [comment]
Good points @kipcole9. Rationale around `non-!` variant perfectly makes sense. 
Let's merge and see from there based on feedback then

**Comment by akash-akya** [comment]
@kipcole9 on second thought, I am thinking of keeping `@spec concurrency_get() :: integer()` and fixing the return value instead, since this value can never return error. 

I'll push that change, let me know if you have any concern on that

**Comment by kipcole9** [comment]
@akash-akya , looks great and works as expected in my testing.  No issue at all on changing the return type of `concurrency_get/0`. With that change (and a lot of persuasion) dialyzer is now green on `Image`.  Very release-ready in my opinion :-)

**Comment by akash-akya** [comment]
That's nice! released [v0.14.0](https://hex.pm/packages/vix/0.14.0) 🎉

**Pull request merged**
