### PR TITLE
Add support for pre-compiled NIF and libvips

### PR DESCRIPTION
**Pull request by akash-akya**
* precompiled libvips are pulled from - https://github.com/akash-akya/sharp-libvips. Which itself is based on https://github.com/lovell/sharp-libvips. So huge thanks to sharp team. `Vix.LibvipsPrecompiled` is to help with pulling libvips _during the pre compilation_. 
* we use elixir-make to precompile NIF and bundle NIF and libvips. This is what everyone will fetch when using Vix.
* option to use platform provided libvips
*  update documentation and GitHub actions 

**TODO: Need to verify precompile GitHub action an release once**

### CODE REVIEW

**Comment by akash-akya** [comment]
@kipcole9 can you help to review this whenever you are free?

**Comment by akash-akya** [comment]
@kipcole9 ping, in case you missed.
Let me know if you are occupied 😅, I'll just merge this after another look.

**Comment by kipcole9** [comment]
Akash, Apologies, will review today for sure (my day is just starting).Sent from my iPhoneOn 11 Jan 2023, at 06:45, Akash Hiremath ***@***.***> wrote:﻿
@kipcole9 ping, in case you missed.
Let me know if you are occupied 😅, I'll just merge this after another look.

**Comment by akash-akya** [comment]
Seems you are occupied 😅, going ahead with merging to get feedback. Let me know if you face any issues in Image

**Pull request merged**
